name: Build Preview

on:
    pull_request:
        branches:
            - master

jobs:
    build_preview:
        if: "!contains(github.event.head_commit.message, '[skip-build]')"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
              uses: actions/checkout@v3

            - name: Retrieve npm cache (if any)
              uses: actions/cache@v3
              with:
                  path: ~/.npm
                  key: npm-packages

            - name: Install Dependencies
              run: npm install

            - name: Build files
              run: npm run build

            - name: Output event payload
              run: cp $GITHUB_EVENT_PATH ./

            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: dist
                  path: |
                    dist
                    firebase.json
                    .firebaserc
                  retention-days: 1
